REDIS_HOST = 'red-cnua537109ks73fefs0g'
#REDIS_HOST = 'localhost'
REDIS_PORT = 6379

AWS_ACCESS_KEY_ID = 'YCAJE9Z7kcFQJrHKuIBvOtRxY'
AWS_SECRET_ACCESS_KEY = 'YCO8qhlcCNOxgiCqA_2AGTVZcvPfVNpZ3SvlYHBW'
BUCKET = 'hw-bot'
